---
variables:
  - &dhub https://index.docker.io/v1/
  - &reg docker.io
  - &repo bksolutions
  - &app buildah-multiarch
  - &tag v0.0.1"
  - &manifest multiarch
  - &buildpath .




when:
  - event: [push,manual]
    branch: main


steps:
  manifest:
    image: quay.io/buildah/stable
    commands:
      - buildah manifest create *manifest
